function qwran(){window.open("https://apps.apple.com/us/app/quran-majeed-%D8%A7%D9%84%D9%82%D8%B1%D8%A7%D9%86-%D8%A7%D9%84%D9%83%D8%B1%D9%8A%D9%85/id365557665","_self")}
function pl(){window.open("https://apps.apple.com/us/app/7-planets/id478895559","_self")}
function fl(){window.open("https://apps.apple.com/us/app/fleeting-journey/id1400061164","_self")}
function vshack(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/vshack.plist","_self")}
function vspro(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/vspro","_self")}
function djay(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/djay","_self")}
function cute(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/cute","_self")}
function picsart(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/picsart","_self")}
function vspro12(){window.open("itms-services://?action=download-manifest&amp;url=https://ittza7aa.com/plist/vspro12","_self")}
